from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional
import math

from app.utils.auth import get_optional_firebase_token
from app.services.recommender_service import (
    generate_conversational_learning_plan,
    explain_recommendation_item,
    adapt_learning_roadmap,
    milestone_ai_chat,
    generate_diagnostic_quiz,
    generate_project_spec,
    validate_checkpoint_submission,
)
from app.services.storage_service import save_active_roadmap, save_student_profile

router = APIRouter(prefix="/api/v1/recommend", tags=["AI Learning Path Recommender"])


class ConversationalPlanRequest(BaseModel):
    goal: str = Field(..., description="Natural language goal from learner")
    profile: Optional[Dict[str, Any]] = Field(default_factory=dict)


class ExplainRequest(BaseModel):
    item_type: str = Field(default="milestone", description="course|project|milestone|resource")
    item_title: str
    goal: Optional[str] = ""
    learner_profile: Optional[Dict[str, Any]] = Field(default_factory=dict)


class AdaptRoadmapRequest(BaseModel):
    current_roadmap: Dict[str, Any]
    feedback_type: str = Field(..., description="too_hard|too_easy|already_known|more_projects|accelerate")
    target_milestone_id: Optional[str] = None
    user_notes: Optional[str] = None


class MilestoneChatRequest(BaseModel):
    milestone_context: Dict[str, Any]
    chat_history: List[Dict[str, str]] = Field(default_factory=list)
    user_query: str


class DiagnosticQuizRequest(BaseModel):
    skill_name: str
    difficulty: Optional[str] = "intermediate"


class GenerateProjectRequest(BaseModel):
    domain: str
    milestone_title: str
    skills: List[str] = Field(default_factory=list)
    experience_level: Optional[str] = "Intermediate"


class CheckpointValidateRequest(BaseModel):
    milestone_title: str
    checkpoint_goal: str
    submission_text: str


class AdoptRoadmapRequest(BaseModel):
    roadmap: Dict[str, Any]
    user_id: Optional[str] = None


@router.post("/conversational-plan")
async def route_conversational_plan(
    body: ConversationalPlanRequest,
    user_id: Optional[str] = Depends(get_optional_firebase_token),
):
    result = await generate_conversational_learning_plan(body.goal, body.profile)
    return {"status": "success", "plan": result, "user_id": user_id}


@router.post("/explain")
async def route_explain_recommendation(body: ExplainRequest):
    result = await explain_recommendation_item(
        body.item_type,
        body.item_title,
        body.goal,
        body.learner_profile,
    )
    return {"status": "success", "explanation": result}


@router.post("/adapt")
async def route_adapt_roadmap(body: AdaptRoadmapRequest):
    result = await adapt_learning_roadmap(
        body.current_roadmap,
        body.feedback_type,
        body.target_milestone_id,
        body.user_notes,
    )
    return {"status": "success", **result}


@router.post("/chat")
async def route_milestone_chat(body: MilestoneChatRequest):
    result = await milestone_ai_chat(
        body.milestone_context,
        body.chat_history,
        body.user_query,
    )
    return {"status": "success", **result}


@router.post("/diagnostic-quiz")
async def route_diagnostic_quiz(body: DiagnosticQuizRequest):
    result = await generate_diagnostic_quiz(body.skill_name, body.difficulty)
    return {"status": "success", "quiz": result}


@router.post("/generate-project")
async def route_generate_project(body: GenerateProjectRequest):
    result = await generate_project_spec(
        body.domain,
        body.milestone_title,
        body.skills,
        body.experience_level,
    )
    return {"status": "success", "project": result}


@router.post("/validate-checkpoint")
async def route_validate_checkpoint(body: CheckpointValidateRequest):
    result = await validate_checkpoint_submission(
        body.milestone_title,
        body.checkpoint_goal,
        body.submission_text,
    )
    return {"status": "success", "evaluation": result}


@router.post("/adopt")
async def route_adopt_roadmap(
    body: AdoptRoadmapRequest,
    user_id: Optional[str] = Depends(get_optional_firebase_token),
):
    target_uid = body.user_id or user_id
    if not target_uid:
        return {"status": "success", "message": "No authenticated user ID, skipped remote storage"}

    plan = body.roadmap or {}
    try:
        # 1. Build career decision
        career_title = plan.get("target_career") or plan.get("title", "Personalized AI Learning Path")
        career_decision = {
            "career": career_title,
            "reasoning": plan.get("summary") or plan.get("explainability", {}).get("why_this_path", "Personalized roadmap generated by AI"),
            "confidence": plan.get("match_score", 88),
            "skill_match_percentage": plan.get("readiness_score", 65),
            "market_readiness": plan.get("readiness_score", 65),
            "industry_demand": "trending",
            "time_to_job_ready": f"{plan.get('weeks_to_readiness', 6)} weeks",
            "key_strengths": plan.get("explainability", {}).get("strengths_leveraged", ["Core fundamentals", "Fast learner"]),
            "skill_gaps": plan.get("explainability", {}).get("top_skill_gaps_addressed", ["Applied Architecture", "Testing"]),
            "alternatives": []
        }

        # 2. Build learning roadmap phases
        converted_phases = []
        all_skills = []
        for idx, ph in enumerate(plan.get("phases", [])):
            milestones = []
            phase_skills = []
            for m in ph.get("milestones", []):
                for s in m.get("skills", []):
                    if s not in phase_skills:
                        phase_skills.append(s)
                    if s not in all_skills:
                        all_skills.append(s)
                milestones.append({
                    "name": m.get("title"),
                    "skills": m.get("skills", []),
                    "resources": m.get("resources", []),
                    "status": "completed" if m.get("completed") else "pending"
                })
            converted_phases.append({
                "phase": ph.get("phase_name", f"Phase {idx+1}: Core Progression"),
                "duration": ph.get("timeline", "Weeks 1-2"),
                "difficulty": ph.get("difficulty", "intermediate"),
                "focus_skills": phase_skills,
                "outcomes": [m.get("checkpoint_project") for m in ph.get("milestones", []) if m.get("checkpoint_project")] or [f"Master {ph.get('phase_name')}"],
                "milestones": milestones,
                "prerequisites": ph.get("prerequisites", []),
                "status": "pending",
                "completed_at": None,
                "estimated_hours": ph.get("estimated_hours", 15)
            })

        weeks = plan.get("weeks_to_readiness") or 6
        roadmap_obj = {
            "duration_months": max(1, math.ceil(weeks / 4)),
            "roadmap": converted_phases,
            "total_estimated_hours": plan.get("total_estimated_hours", 64),
            "weeks_to_readiness": weeks,
            "raw_plan": plan,
        }

        # 3. Save active roadmap to Firestore
        await run_in_threadpool(
            save_active_roadmap,
            target_uid,
            career_decision,
            roadmap_obj,
            preserve_progress=False
        )

        # 4. Save/update student profile in Firestore so profile page reflects it
        profile_data = {
            "name": "LevelUP Learner",
            "goals": career_title,
            "skills": ", ".join(all_skills[:12]) if all_skills else "Fullstack Engineering, AI",
            "interests": career_title,
            "experience": f"{plan.get('weekly_hours', 10)} hours/week study commitment"
        }
        await run_in_threadpool(save_student_profile, target_uid, profile_data)

        return {
            "status": "success",
            "message": "Roadmap and student profile saved successfully to Firestore",
            "user_id": target_uid,
            "career": career_title,
            "phases_count": len(converted_phases)
        }

    except Exception as e:
        print(f"Error adopting recommender roadmap: {e}")
        return {"status": "error", "message": f"Failed to persist: {str(e)}", "user_id": target_uid}
